#!/usr/bin/env node
/**
 * generate-config.js
 *
 * Reads REACT_APP_BACKEND_URL from the .env file (or process.env) and
 * writes public/config.js — a runtime config loaded by static HTML pages.
 *
 * Usage:
 *   node scripts/generate-config.js
 *
 * On Render / Fly.io / Railway: set REACT_APP_BACKEND_URL as an environment
 * variable in the platform dashboard. Run this script in the build step:
 *   node scripts/generate-config.js && npx serve . -l $PORT
 */

const fs = require('fs');
const path = require('path');

// Load .env if present (manual simple parser — no dotenv dependency needed)
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (!process.env[key]) {
      process.env[key] = val;
    }
  }
}

const backendUrl = process.env.REACT_APP_BACKEND_URL || 'http://localhost:8000';

const configContent = `/* AUTO-GENERATED by scripts/generate-config.js — DO NOT EDIT MANUALLY */
/* To change the backend URL, update .env and re-run: node scripts/generate-config.js */
window.SENTINEL_BACKEND_URL = "${backendUrl}";
`;

const outputPath = path.join(__dirname, '..', 'config.js');
fs.writeFileSync(outputPath, configContent, 'utf8');

console.log(`✅ Generated config.js with SENTINEL_BACKEND_URL="${backendUrl}"`);
// Also write to public/ so react-scripts build picks it up
const publicOutputPath = path.join(__dirname, '..', 'public', 'config.js');
try { fs.writeFileSync(publicOutputPath, configContent, 'utf8'); } catch (e) {}
